// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlungwerloclwtawifxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJsdW5nd2VybG9jbHd0YXdpZnhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODA1NjksImV4cCI6MjA2MDQ1NjU2OX0.rqZrbE338P2S5IjsSeckfPcOaf0E_ixIwsU97N5gkFs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);