
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://yesygkeuiiexjnlylvwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inllc3lna2V1aWlleGpubHlsdndvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5MzM1NDUsImV4cCI6MjA2NjUwOTU0NX0.ZY8-2xAqjzCdjWuBKGHZzYNl4X3ajwWGyfCBEjr295o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
